---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(nycflights13)
view(planes)
view(airlines)
view(airports)
view(flights)
view(weather)

```

1. Inner-Join
```{r}
#1.1
flights%>%
  inner_join(planes, by = "tailnum")
#1.2
flights%>%
  inner_join(airlines, by = "carrier")
#1.3
flights%>%
  inner_join(airports, by = c("origin" = "faa"))%>%
  inner_join(airports, by = c("dest" = "faa"))
#1.4
flights%>%
  inner_join(weather, by = c("year", "month", "day", "hour", "origin"))
```
2. Data manipulation

```{r}
#2.1
flights%>%
  count(year, month, day)%>%
  filter(n > 1000)%>%
  arrange(n)
```

```{r}
#2.2
flights_selected = flights%>%
dplyr::select(year:day, hour, origin, dest, tailnum, carrier, arr_delay, dep_delay)

flights_selected
```

```{r}
#2.3
airlines%>%
  left_join(flights_selected, by = "carrier")%>%
dplyr::select(-origin, -dest)%>%
  mutate(tot_delay = arr_delay + dep_delay)
```

```{r}
#2.4
precip_delay = flights%>%
  inner_join(weather, by = c("year", "month", "day", "hour", "origin"))%>%
  group_by(precip)%>%
  summarise(delay = mean(dep_delay, na.rm=TRUE))%>%
  replace_na(list(delay = 0 ))

precip_delay
```

```{r}
#2.5
ggplot(precip_delay, aes(x = precip, y = delay, )) + 
  geom_point() 
```

```{r}
#2.6
flights_airports = flights%>%
  filter(year==2013, month ==5, day == 10)%>%
  group_by(dest)%>%
  summarise(delay = mean(arr_delay, na.rm=TRUE))%>%
  inner_join(airports, by = c("dest" = "faa"))

flights_airports
```

```{r}
#2.7
ggplot(flights_airports, aes(x = lon, y = lat, color = delay, size = delay)) + 
  geom_point() 
```
```{r}
#2.8
flights%>%
  inner_join(planes, by = "tailnum", suffix=c("_flights", "_planes"))%>%
  transmute(tailnum, manufacturer, pi = (dep_delay + arr_delay)/air_time)
```







